### PR TITLE
Fix: regexes with forward slashes are printed with extra escaping

### PR DESCRIPTION
**Pull request by Gozala**

### CODE REVIEW

**Comment by Gozala** [comment]
Fixed. In fact I used single `;` to be consistent with other comments in that function so I update them too, to stay consistent.

**Comment by kanaka** [comment]
Actually, I've reconsidered the double-semi colon. It looks like it's not as strict of a coding style as I thought. It's better not add superfluous changes to existing upstream code. Please just make comma and plural change. Sorry for the run-around.

**Comment by Gozala** [comment]
np. I squashed changes to avoid useless commits in history.

**Comment by kanaka** [comment]
Perfect. Merged.

**Pull request merged**
