### PR TITLE
File editor for web repl

### PR DESCRIPTION
**Pull request by arthuredelstein**
File editor for web repl:
1. Create a CodeMirror-based file editor (in webedit.cljs)
2. Create webrepl3.cljs and repl3.html, which use the file editor
3. build2.sh builds the console-only version of clojurescript.net;
   build3.sh builds the version including both console and file editor.

The file editor's contents can be evaluated in the REPL by pressing
Ctrl/Cmd+E, and the editor itself can be shown and hidden by pressing
the Show/Hide file editor link.

### CODE REVIEW

**Comment by kanaka** [comment]
I haven't looked in detail at the changes, but please make codemirror into a submodule instead pulling the whole thing into tree (this pull has 246 changed files). Also, make sure to rebase so that it's not polluting the history. Thanks.

**Comment by kanaka** [comment]
BTW, if you rebase the same branch and then force push to that branch github will automatically update the pull request with the new rewritten branch.

**Comment by arthuredelstein** [comment]
OK, fixed. Thanks for your git help!

**Comment by arthuredelstein** [comment]
One more change just squashed in because of a missing addition to himera.css.

**Comment by kanaka** [comment]
Merged. clojurescript.net is also updated.

@arthuredelstein, also, can you fill out and mail in the Clojure contributor agreement? http://clojure.org/contributing 

The upstream Clojure and ClojureScript projects only accept patches from people that have signed the contributor agreement. At some point I will be pushing the cljs-in-cljs changes upstream. I don't know if that will include the web REPL or not (or maybe just some of the repl related functions), but if you get the contributor agreement taken care of now then it will make life much easier later. Thanks!

**Comment by arthuredelstein** [comment]
I'm registered as a contributor now.

**Comment by kanaka** [comment]
Arthur,

Excellent! Thanks.

Joel Martin (kanaka)

**Pull request merged**
