### PR TITLE
Fix for numeric keywords #7

### PR DESCRIPTION
**Pull request by Gozala**
This is a fix for numeric keywords #7 bug. In addition I discovered behavioral difference in keyword function between clojure & clojurescript & fixed that too as it was necessary for
fixing original bug.

### CODE REVIEW

**Comment by Gozala** [comment]
So far I have being doing repl based testing

``` clojure
(assert (identical? (namespace :foo) nil) "ns isn't nil")
(assert (identical? (name :foo) "foo") "name isn't foo")
(assert (identical? (name ::foo) "foo") "name isn't foo")
(assert (identical? (namespace ::foo) (str *ns-sym*)) "wrong ns")

(assert (identical? (namespace :1) nil) "ns isn't nil")
(assert (identical? (name :1) \1) "name isn't 1")
(assert (identical? (namespace ::2) (str *ns-sym*)) "wrong ns")
(assert (identical? (name ::2) \2) "name isn't 2")
```

I'll spend time on figuring out how to actually run tests & will integrate these assertios

**Comment by kanaka** [comment]
I run tests using load-file:

```
(load-file "../test/cljs/cljs/quick.cljs")
(run-tests)
(load-file "../test/cljs/cljs/core_test.cljs")
(test-stuff)
```

core_test.cljs is from upstream and there are a bunch of broken parts to it still (including the bugs I filed). quick.cljs should pass. You can add those assertions to that file for now.

**Comment by Gozala** [comment]
@kanaka so I was trying:

``` clojure
(load-file "../test/cljs/cljs/core_test.cljs")
cljs.user=> (load-file "../test/cljs/cljs/core_test.cljs")
ERR: Error: Invalid number format [0x7e7]
ERR:     at reader_error__delegate (../cljs/reader.js:149:8)
ERR:     at reader_error (../cljs/reader.js:156:31)
ERR:     at read_number (../cljs/reader.js:514:34)
ERR:     at read__4 (../cljs/reader.js:1355:137)
ERR:     at read (../cljs/reader.js:1387:16)
ERR:     at read_delimited_list (../cljs/reader.js:445:26)
ERR:     at read_vector (../cljs/reader.js:482:40)
ERR:     at read_delimited_list (../cljs/reader.js:437:20)
ERR:     at read_list (../cljs/reader.js:478:81)
ERR:     at read_delimited_list (../cljs/reader.js:437:20)
```

Did you get the same ? I suspect that's #9 but wanna make sure.
P.S.: I get that error with & without my changes

**Comment by kanaka** [comment]
@Gozala regarding core_test.cljs, yes, that error is #9. Also, here is a version of core_test.cljs that has breaking tests/asserts commented out (with TODOs) and also some progress print out so that it is easier to tell which part of the file is breaking: https://gist.github.com/4574095

**Pull request merged**
