### PR TITLE
Scratch file editor for clojurescrit.net

### PR DESCRIPTION
**Pull request by arthuredelstein**
- "Show/hide file editor" link
- Evaluation of file (Cmd/Ctrl+E) returns error or value of last evaluated form
- User feedback during file evaluation: "Evaluating file..."
- More helpful error messages
- *e works in REPL

See demo at http://arthuredelstein.github.com/clojurescript/web/repl.html

### CODE REVIEW

**Comment by kanaka** [comment]
I get the following error from the demo page and the console doesn't start:
Uncaught TypeError: Object Linux x86_64 has no method 'contains' qndfC.js:225

Also, I just pushed an update that refactors the shared repl code to src/cljs/cljs/repl.cljs. This is now shared by webrepl.cljs, webrepl2.cljs, noderepl.cljs and nodecljs.cljs. It's incompatible with your current set of changes.

Some other changes I would like to see:
- do this in a separate webrepl3.cljs/repl3.html or similar. At some point I will probably remove/merge the different web repls, but for now I'm not sure which combination of features should be default and want to keep some of the simpler versions availble. Also, try and make it modular and have shared or general REPL functionality in src/cljs/cljs/repl.cljs like what I just pushed.
- rework/rebase your changes to make the history cleaner by removing reverts and branch merges.
- group the commits so they are logical chunks (you can do this with interactive rebase or cherry picking). combine bug fix and cleanup commits into the commits that introduced the feature.

Thanks!

**Comment by arthuredelstein** [comment]
I've made some more bug fixes. Does it work for you now?
http://arthuredelstein.github.com/clojurescript/web/repl.html

> rework/rebase your changes to make the history cleaner by removing reverts and branch merges.
> group the commits so they are logical chunks 

Good suggestions. I wasn't aware of interactive rebase.

> do this in a separate webrepl3.cljs/repl3.html or similar.

Do you think a scratch file editor as I've been implementing is something you would be willing to include on clojurescript.net? Or do you think you would prefer a simple repl as is already there?

**Comment by kanaka** [comment]
Great. The example is looking good.

Yeah, rebase is great. Just note that if there is any chance somebody else has pulled down a branch then using rebase on that branch will completely screw them up. In other words, it is rewriting git history, so it's a "dangerous" operation. However, as long as you only rebase changes you haven't pushed, or in this case rebase in a fork that you are just using for pull requests, then you should be all set.

Yeah, I will probably make the version with your editor the default on clojurescript.net once it's cleaned up and I merge it. However, I would still like to keep it separate and have the simpler options (the plain jsrepl.html and the current repl.html) accessible from my gh-pages site. That's why I want them separate for now.

**Comment by kanaka** [comment]
@arthuredelstein I'm going to close this pull request since you are working on significantly refactoring these changes.

**Pull request closed without merging**
